
export interface Scientist {
  name: string;
  area: string;
  contribution: string;
  nationality: string;
  bio: string;
  category: string[];
}

export const scientists: Scientist[] = [
  {
    name: "Hipátia de Alexandria",
    area: "Filosofia, Matemática e Astronomia",
    contribution: "Primeira mulher matemática conhecida na história, contribuições em astronomia e filosofia.",
    nationality: "Egípcia (Alexandria)",
    bio: "Hipátia de Alexandria (c. 351/370 – 415 d.C.) foi uma filósofa neoplatônica, astrônoma e matemática que viveu em Alexandria, Egito. Ela foi a primeira mulher matemática conhecida na história e uma proeminente pensadora de sua época, ensinando filosofia e astronomia na Academia de Alexandria.",
    category: ["Mulheres não-negras", "Clássicos Famosos"],
  },
  {
    name: "Bartolomeu de Gusmão",
    area: "Invenção",
    contribution: "Desenvolveu o primeiro balão de ar quente funcional.",
    nationality: "Brasileiro (Colônia)",
    bio: "Bartolomeu Lourenço de Gusmão (1685-1724) foi um sacerdote jesuíta, naturalista e inventor nascido na colônia portuguesa do Brasil. Ele é conhecido por suas contribuições pioneiras na aerostação, tendo desenvolvido o primeiro balão de ar quente funcional, o que lhe rendeu o apelido de \"Padre Voador\".",
    category: ["Homens Brasileiros", "Clássicos Famosos"],
  },
  {
    name: "Ada Lovelace",
    area: "Matemática e Ciência da Computação",
    contribution: "Considerada a primeira programadora de computador do mundo, por seu trabalho na Máquina Analítica de Charles Babbage.",
    nationality: "Britânica",
    bio: "Ada Lovelace (1815-1852) foi uma matemática e escritora britânica, filha do poeta Lord Byron. Ela é amplamente reconhecida por seu trabalho na Máquina Analítica de Charles Babbage, uma máquina mecânica de uso geral. Suas anotações sobre o motor incluem o que é reconhecido como o primeiro algoritmo destinado a ser processado por uma máquina, tornando-a a primeira programadora de computador do mundo.",
    category: ["Mulheres não-negras", "Clássicos Famosos"],
  },
  {
    name: "Louis Pasteur",
    area: "Química e Microbiologia",
    contribution: "Desenvolveu a pasteurização e vacinas contra raiva e antraz, provando a teoria dos germes.",
    nationality: "Francês",
    bio: "Louis Pasteur (1822-1895) foi um químico e microbiologista francês, amplamente considerado um dos fundadores da microbiologia médica. Suas descobertas mais notáveis incluem os princípios da vacinação, da fermentação microbiana e da pasteurização. Ele é lembrado por suas inovações nas causas e prevenção de doenças, que salvaram inúmeras vidas.",
    category: ["Clássicos Famosos", "Mulheres não-negras"], 
  },
  {
    name: "Adolfo Lutz",
    area: "Medicina Tropical",
    contribution: "Pioneiro na medicina tropical no Brasil, identificou o mosquito Aedes aegypti como transmissor da febre amarela.",
    nationality: "Brasileiro",
    bio: "Adolfo Lutz (1855-1940) foi um médico e cientista brasileiro, um dos maiores nomes da medicina tropical no país. Ele foi fundamental na identificação do mosquito Aedes aegypti como vetor da febre amarela e realizou extensas pesquisas sobre diversas doenças infecciosas, como hanseníase, peste bubônica e leishmaniose.",
    category: ["Homens Brasileiros", "Clássicos Famosos"],
  },
  {
    name: "Max Planck",
    area: "Física",
    contribution: "Fundador da teoria quântica, que revolucionou a compreensão da energia em nível atômico e subatômico.",
    nationality: "Alemão",
    bio: "Max Karl Ernst Ludwig Planck (1858-1947) foi um físico teórico alemão cuja descoberta dos quanta de energia lhe valeu o Prêmio Nobel de Física em 1918. Ele é considerado o fundador da teoria quântica, um dos pilares da física moderna, que descreve o comportamento da matéria e da energia em escalas atômicas e subatômicas.",
    category: ["Clássicos Famosos", "Mulheres não-negras"], 
  },
  {
    name: "Marie Curie",
    area: "Física e Química",
    contribution: "Pioneira na pesquisa sobre radioatividade, primeira mulher a ganhar um Prêmio Nobel.",
    nationality: "Polonesa/Francesa",
    bio: "Marie Skłodowska Curie (1867-1934) foi uma física e química polonesa naturalizada francesa que conduziu pesquisas pioneiras sobre radioatividade. Ela foi a primeira mulher a ganhar um Prêmio Nobel, a primeira pessoa e única mulher a ganhar o Prêmio Nobel duas vezes, e a única pessoa a ganhar o Prêmio Nobel em duas ciências diferentes.",
    category: ["Mulheres não-negras", "Clássicos Famosos"],
  },
  {
    name: "Oswaldo Cruz",
    area: "Medicina e Saúde Pública",
    contribution: "Liderou campanhas de erradicação de doenças como febre amarela, varíola e peste bubônica no Brasil.",
    nationality: "Brasileiro",
    bio: "Oswaldo Gonçalves Cruz (1872-1917) foi um médico, bacteriologista e sanitarista brasileiro. Ele foi uma figura central na história da saúde pública no Brasil, liderando campanhas de erradicação de epidemias como febre amarela, varíola e peste bubônica no início do século XX. Fundou o Instituto Soroterápico Federal, que mais tarde se tornaria a Fundação Oswaldo Cruz (Fiocruz).",
    category: ["Homens Brasileiros", "Clássicos Famosos"],
  },
  {
    name: "Vital Brazil",
    area: "Medicina e Pesquisa",
    contribution: "Desenvolveu o soro antiofídico e foi pioneiro na soroterapia no Brasil.",
    nationality: "Brasileiro",
    bio: "Vital Brazil Mineiro da Campanha (1865-1950) foi um médico, imunologista e pesquisador brasileiro. Ele é mundialmente reconhecido por suas pesquisas com venenos de animais peçonhentos e pelo desenvolvimento do soro antiofídico, que revolucionou o tratamento de picadas de cobras. Fundou o Instituto Butantan e o Instituto Vital Brazil.",
    category: ["Homens Brasileiros", "Clássicos Famosos"],
  },
  {
    name: "Carlos Chagas",
    area: "Medicina",
    contribution: "Descobriu a Doença de Chagas e seu agente causador, o Trypanosoma cruzi.",
    nationality: "Brasileiro",
    bio: "Carlos Ribeiro Justiniano Chagas (1879-1934) foi um médico sanitarista e cientista brasileiro. Ele é o único cientista na história da medicina a descrever completamente uma doença infecciosa: o patógeno (Trypanosoma cruzi), o vetor (barbeiro), o hospedeiro, as manifestações clínicas e a epidemiologia da Doença de Chagas.",
    category: ["Homens Brasileiros", "Clássicos Famosos"],
  },
  {
    name: "Albert Einstein",
    area: "Física",
    contribution: "Desenvolveu a Teoria da Relatividade, que revolucionou a física moderna.",
    nationality: "Alemão/Americano",
    bio: "Albert Einstein (1879-1955) foi um físico teórico que desenvolveu a teoria da relatividade, um dos dois pilares da física moderna. Seu trabalho também é conhecido por sua influência na filosofia da ciência. Ele é mais conhecido pela fórmula de equivalência massa-energia E=mc², que foi apelidada de \"a equação mais famosa do mundo\". Recebeu o Prêmio Nobel de Física em 1921 por suas explicações sobre o efeito fotoelétrico.",
    category: ["Clássicos Famosos", "Mulheres não-negras"], 
  },
  {
    name: "Ernest Everett Just",
    area: "Biologia",
    contribution: "Pioneiro no estudo da biologia celular e do desenvolvimento embrionário.",
    nationality: "Americano",
    bio: "Ernest Everett Just (1883-1941) foi um biólogo e educador americano, pioneiro no estudo da biologia celular e do desenvolvimento embrionário. Ele fez contribuições significativas para a compreensão da fertilização e da partenogênese.",
    category: ["Homens Negros", "Clássicos Famosos"],
  },
  {
    name: "St. Elmo Brady",
    area: "Química",
    contribution: "Primeiro afro-americano a obter um doutorado em química nos EUA.",
    nationality: "Americano",
    bio: "St. Elmo Brady (1884-1966) foi um químico americano e o primeiro afro-americano a obter um doutorado em química nos Estados Unidos. Ele dedicou sua carreira ao ensino e à pesquisa em universidades historicamente negras.",
    category: ["Homens Negros", "Clássicos Famosos"],
  },
  {
    name: "Alice Augusta Ball",
    area: "Química",
    contribution: "Desenvolveu o primeiro tratamento eficaz para a hanseníase usando óleo de chaulmoogra.",
    nationality: "Americana",
    bio: "Alice Augusta Ball (1892-1916) foi uma química americana que desenvolveu o \"Método Ball\", o tratamento mais eficaz para a hanseníase durante o início do século XX. Ela foi a primeira mulher e a primeira afro-americana a se formar com um mestrado na Universidade do Havaí e a primeira professora de química na mesma universidade.",
    category: ["Mulheres Negras", "Clássicos Famosos"],
  },
  {
    name: "S. Chandrasekhar",
    area: "Astrofísica",
    contribution: "Trabalho teórico sobre a estrutura e evolução estelar, incluindo o limite de Chandrasekhar.",
    nationality: "Indiano/Americano",
    bio: "Subrahmanyan Chandrasekhar (1910-1995) foi um astrofísico indiano-americano que, com William A. Fowler, ganhou o Prêmio Nobel de Física de 1983 por seus estudos teóricos dos processos físicos importantes para a estrutura e evolução das estrelas.",
    category: ["Homens Negros", "Clássicos Famosos"],
  },
  {
    name: "Enedina Alves Marques",
    area: "Engenharia Civil",
    contribution: "Primeira engenheira negra do Brasil e primeira mulher a se formar em engenharia no Paraná.",
    nationality: "Brasileira",
    bio: "Enedina Alves Marques (1913-1994) foi uma engenheira civil brasileira. Ela foi a primeira engenheira negra do Brasil e a primeira mulher a se formar em engenharia no estado do Paraná. Contribuiu para grandes obras de infraestrutura no estado.",
    category: ["Mulheres Negras", "Mulheres Negras Brasileiras"],
  },
  {
    name: "Kenneth Clark",
    area: "Psicologia",
    contribution: "Seu trabalho sobre os efeitos da segregação racial em crianças foi fundamental para o caso Brown v. Board of Education.",
    nationality: "Americano",
    bio: "Kenneth Bancroft Clark (1914-2005) foi um psicólogo americano e ativista dos direitos civis. Juntamente com sua esposa, Mamie Phipps Clark, ele conduziu o famoso \"teste das bonecas\", que demonstrou os efeitos psicológicos da segregação racial em crianças. Seu trabalho foi citado na decisão da Suprema Corte dos EUA no caso Brown v. Board of Education, que declarou a segregação escolar inconstitucional.",
    category: ["Homens Negros", "Clássicos Famosos"],
  },
  {
    name: "Mamie Phipps Clark",
    area: "Psicologia Social",
    contribution: "Seu trabalho sobre o desenvolvimento da auto-estima em crianças negras foi fundamental para o caso Brown v. Board of Education.",
    nationality: "Americana",
    bio: "Mamie Phipps Clark (1917-1983) foi uma psicóloga social americana que, juntamente com seu marido Kenneth Clark, conduziu o famoso \"teste das bonecas\", que demonstrou os efeitos prejudiciais da segregação racial na auto-estima de crianças negras. Seu trabalho foi crucial para a decisão da Suprema Corte dos EUA no caso Brown v. Board of Education, que declarou a segregação escolar inconstitucional.",
    category: ["Mulheres Negras", "Clássicos Famosos"],
  },
  {
    name: "Katherine Johnson",
    area: "Matemática",
    contribution: "Cálculos de trajetórias para o Projeto Mercury e o voo da Apollo 11 à Lua.",
    nationality: "Americana",
    bio: "Katherine Johnson (1918-2020) foi uma matemática americana cujos cálculos da mecânica orbital como funcionária da NASA foram cruciais para o sucesso dos primeiros e tripulados voos espaciais dos EUA. Ela foi uma das \"computadoras\" humanas que realizaram cálculos complexos para as missões espaciais, incluindo o voo de John Glenn e a Apollo 11.",
    category: ["Mulheres Negras", "Clássicos Famosos"],
  },
  {
    name: "José Leite Lopes",
    area: "Física",
    contribution: "Importantes contribuições para a física teórica e fundação de instituições científicas no Brasil.",
    nationality: "Brasileiro",
    bio: "José Leite Lopes (1918-2006) foi um físico teórico brasileiro. Ele fez contribuições significativas para a física de partículas e foi um dos fundadores do Centro Brasileiro de Pesquisas Físicas (CBPF) e do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq). Recebeu o Prêmio UNESCO Science Prize em 1989.",
    category: ["Homens Brasileiros", "Clássicos Famosos"],
  },
  {
    name: "Charles E. Anderson",
    area: "Meteorologia",
    contribution: "Primeiro afro-americano a obter um doutorado em meteorologia.",
    nationality: "Americano",
    bio: "Charles E. Anderson (1919-1994) foi um meteorologista americano e o primeiro afro-americano a obter um doutorado em meteorologia. Ele foi um pioneiro na pesquisa de nuvens e tempestades e atuou como reitor na Universidade de Wisconsin.",
    category: ["Homens Negros", "Clássicos Famosos"],
  },
  {
    name: "David Blackwell",
    area: "Estatística e Matemática",
    contribution: "Contribuições significativas para a teoria da estatística, incluindo o teorema de Rao-Blackwell.",
    nationality: "Americano",
    bio: "David Harold Blackwell (1919-2010) foi um estatístico e matemático americano. Ele foi o primeiro afro-americano a ser eleito para a Academia Nacional de Ciências dos Estados Unidos e fez contribuições significativas para a teoria da estatística, incluindo o teorema de Rao-Blackwell.",
    category: ["Homens Negros", "Clássicos Famosos"],
  },
  {
    name: "Cesar Lattes",
    area: "Física de Partículas",
    contribution: "Co-descoberta do méson pi, uma partícula subatômica.",
    nationality: "Brasileiro",
    bio: "Cesare Mansueto Giulio Lattes (1924-2005), mais conhecido como Cesar Lattes, foi um físico brasileiro, um dos descobridores do méson pi, o que levou ao Prêmio Nobel de Física de 1950 para Cecil Powell. Sua pesquisa foi fundamental para o desenvolvimento da física de partículas.",
    category: ["Homens Brasileiros", "Clássicos Famosos"],
  },
  {
    name: "Milton Santos",
    area: "Geografia",
    contribution: "Renomado geógrafo, crítico do neoliberalismo e da globalização, e defensor de uma geografia crítica.",
    nationality: "Brasileiro",
    bio: "Milton Almeida dos Santos (1926-2001) foi um geógrafo brasileiro, um dos maiores pensadores da geografia mundial. Ele é conhecido por suas teorias sobre a globalização, o espaço geográfico e o subdesenvolvimento, sendo um crítico ferrenho do neoliberalismo. Foi o primeiro e único latino-americano a receber o Prêmio Vautrin Lud, considerado o \'Nobel da Geografia\'.",
    category: ["Homens Negros", "Clássicos Famosos", "Homens Brasileiros"],
  },
  {
    name: "Annie Easley",
    area: "Matemática e Ciência da Computação",
    contribution: "Desenvolvimento de software para o estágio de foguete Centaur e pesquisa em tecnologias de energia alternativa na NASA.",
    nationality: "Americana",
    bio: "Annie Easley (1933-2011) foi uma cientista da computação, matemática e cientista de foguetes americana. Ela trabalhou para a NASA e suas antecessoras, o Lewis Research Center e o Glenn Research Center. Easley foi uma das primeiras afro-americanas a trabalhar como cientista da computação na NASA, onde desenvolveu e implementou códigos de computador que analisavam tecnologias de energia alternativa e o estágio de fogeute Centaur.",
    category: ["Mulheres Negras", "Clássicos Famosos"],
  },
  {
    name: "Mae Jemison",
    area: "Engenharia Química e Medicina",
    contribution: "Primeira mulher afro-americana a viajar para o espaço.",
    nationality: "Americana",
    bio: "Mae Carol Jemison (nascida em 1956) é uma engenheira, médica e ex-astronauta da NASA. Ela se tornou a primeira mulher afro-americana a viajar para o espaço quando serviu como especialista de missão a bordo do ônibus espacial Endeavour em 1992.",
    category: ["Mulheres Negras", "Clássicos Famosos"],
  },
];
  

export const categories = [
  "Mulheres Negras",
  "Mulheres não-negras",
  "Homens Negros",
  "Homens Brasileiros",
  "Mulheres Negras Brasileiras",
  "Clássicos Famosos",
];


